namespace cg
{
  public class CPrueba
  {
    private int a;

    public CPrueba(int pA)
    {
      a = pA;
    }
    public override string ToString()
    {

      return string.Format("EL VALOR ES {0}", a);
    }

    //TIPOS FINALIZABLES
    //OBJET ES LA CLASE PADRE DE TODOS LOS TIPOS QUE EXISTEN EN C#
    //OBJECT TIENE UN METODO VIRTUAL LLAMADO FINALIZE()
    //CUANDO SE HACE EL OVERRIDE DE FINALIZE TENEMOS UN LUGAR DONDE LLEVAR A CABO LA LIMPIEZA PARA LA CLASE.
    //NO SE PUEDE INVOCAR DIRECTAMENTE, POR QUE ES UN METODO PROTEGIDO.
    //LO INVOCA EL RECOLECTOR DE BASURA ANTES DE ELIMINAR EL OBJETO DE LA MEMORIA
    //NO SE PUEDE HARE OVERRIDE DE TIPOS ESTRUCTURA.
    //PRACTICAMENTE NUNCA HAREMOS ESTO SALVO QUE TENGAMOS RECURSOS NO ADMINISTRADOS.
    //QUE NECESITEN SER ELEMINADOS MANUALMENTE: PINVOKE, COM, MEMORIA NO ADMINISTRADA.

    //NO HACEMOS USO DE OVERRIDE
    //SE UTILIZA EL DESTRUCTOR PARA ESTO
    ~CPrueba()
    {
      Console.ForegroundColor = ConsoleColor.Red;
      Console.WriteLine("LIBERACION DE RECURSOS NO ADMINISTRADOS");
      Console.Beep();
    }
  }

}